# Generated by Django 3.2.3 on 2023-11-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.CharField(default=1, max_length=200, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
    ]
